#!/bin/sh
touch /var/log/urlsnarf.log
touch /var/log/bot-bashd.log

chown root:adm /var/log/urlsnarf.log
chown root:adm /var/log/bot-bashd.log

/usr/sbin/urlsnarf -ni eth1 \
    | tee -a /var/log/urlsnarf.log \
    | /usr/local/bin/bot-bash \
    >> /var/log/bot-bashd.log \
    &
