#!/bin/sh

function loop() {
    while [ 1 ]
    do
        echo "$(date -u +%FT%TZ) $(cat /proc/loadavg)" >> /var/log/loadlogd.log
        sleep 1
    done
}

touch /var/log/loadlogd.log
chown root:adm /var/log/loadlogd.log
loop &